version: '3.9'

# this docker-compose file is used both to run the app locally (combined with .devcontainer/devcontainer.json)
# and to run the app in production (combined with docker-compose.prod.yml)

services:
  db:
    image: postgres:15
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
