version: '3.9'

# This is the docker-compose file for production

services:
  db:
    image: postgres:15
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
