version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY}
    depends_on:
      - db

# this network is configured in my VPS
networks:
  default:
    name: main-network
