FROM rust:1.60 

RUN cargo install cargo-watch

WORKDIR /app/
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml
# RUN cargo run

COPY ./src ./src 
COPY ./.docker-cache ./target

ENV CARGO_TARGET_DIR=/app/target
CMD ["cargo", "watch", "-x", "run", "-w", "src" ]
