version: "3.9"

services:
  mothership:
    build:
      context: ./mothership
      dockerfile: Dockerfile.dev
    volumes:
      - ./mothership/src:/app/src
      - mothership_cache:/app/target
    depends_on:
      - db

  voice:
    build:
      context: ./voice 
      dockerfile: Dockerfile.dev
    volumes:
      - ./voice/src:/app/src     # actual source code
      - ./voice/media:/app/media # media files
    environment:
      - MEDIA_PATH=/app/media 
    depends_on:
      - db


volumes:
  # caches rust run output
  mothership_cache:
    driver: local
