version: '3'
services:
  editor:
    image: 'mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye'
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
