version: "3.9"

services:
  db:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - cache:/data
  bot:
    environment:
      ENV_PATH: /run/secrets/bot_env
      REDIS_HOST: db
      REDIS_PORT: 6379
      # lol i my redis password safe? Pretty sure you can inspect my docker image and see the password :D 
      REDIS_PASSWORD: ${REDIS_PASS}
    secrets:
      - bot_env

# https://serverfault.com/a/936262
secrets:
  bot_env:
    file: ./.env

volumes:
  # caches rust run output
  cache:
    driver: local
