version: "3.9"

services:
  db:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redisdb:/data

  mothership:
    tty: true
    environment:
      TERM: xterm-256color
      ENV_PATH: /run/secrets/mothership_env
    # common environment variables defined in top level .env file
    # MODE, GUILD_ID, APP_ID, DEVS, REDIS_PASS, REDIS_HOST, REDIS_PORT
    env_file:
      - .env
    secrets:
      - mothership_env

  voice:
    # tty and xterm env makes the logs colourful! 
    # https://github.com/docker/compose/issues/2231#issuecomment-425135985
    tty: true
    environment:
      TERM: xterm-256color
      ENV_PATH: /run/secrets/voice_env
    # common environment variables defined in top level .env file
    # MODE, GUILD_ID, APP_ID, DEVS, REDIS_PASS, REDIS_HOST, REDIS_PORT
    env_file:
      - .env
    secrets:
      - voice_env


# https://serverfault.com/a/936262
secrets:
  mothership_env:
    file: ./mothership/.env
  voice_env:
    file: ./voice/.env


volumes:
  # caches rust run output
  redisdb:
    driver: local
