version: "3.9"

services:
  db:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redisdb:/data
  mothership:
    environment:
      ENV_PATH: /run/secrets/mothership_env
      REDIS_HOST: db
      REDIS_PORT: 6379
      # lol i my redis password safe? Pretty sure you can inspect my docker image and see the password :D 
      REDIS_PASSWORD: ${REDIS_PASS}
      # common environment variables defined in top level .env file
      MODE: ${MODE}
      GUILD_ID: ${GUILD_ID}
    secrets:
      - mothership_env

# https://serverfault.com/a/936262
secrets:
  mothership_env:
    file: ./mothership/.env

volumes:
  # caches rust run output
  redisdb:
    driver: local
