version: "3.9"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - cache:/app/target

volumes:
  # caches rust run output
  cache:
    driver: local
