version: "3.9"

services:
  db:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes:
      - redisdb:/data

  mothership:
    environment:
      ENV_PATH: /run/secrets/mothership_env
      REDIS_HOST: db
      REDIS_PORT: 6379
    # common environment variables defined in top level .env file
    # MODE, REDIS_PASS, GUILD_ID, APP_ID, DEVS
    env_file:
      - .env
    secrets:
      - mothership_env

  voice:
    environment:
      ENV_PATH: /run/secrets/voice_env
    # common environment variables defined in top level .env file
    # MODE, REDIS_PASS, GUILD_ID, APP_ID, DEVS
    env_file:
      - .env
    secrets:
      - voice_env

# https://serverfault.com/a/936262
secrets:
  mothership_env:
    file: ./mothership/.env
  voice_env:
    file: ./voice/.env

volumes:
  # caches rust run output
  redisdb:
    driver: local
