version: '3.9'
services:
  editor:
    build:
      context: .
      dockerfile: .devcontainer/editor.Dockerfile
    volumes:
      - ./:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4:8
    restart: ${RESTART_POLICY}
    ports:
      - 5050:80
