services:
  editor:
    build:
      context: .
      dockerfile: .devcontainer/editor.Dockerfile
    volumes:
      - ./:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - db
