# Development dockerfile
# context is this /voice directory

FROM node:16

# install ffmpeg
# Note that node:16 is based off of debian
RUN apt update && apt install -y ffmpeg

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]
RUN npm ci

COPY . . 
# for some reason, `npm run dev` does not work (exist with code 0)
CMD ["npx", "ts-node-dev", "--watch", "src/**/*.ts", "src/index.ts"]
